### ISSUE TITLE
Questions about file handles and `setBlocking`

### ISSUE THREAD

**Issue by quantimnot** [alaviss/nim-sys#29]
https://github.com/alaviss/nim-sys/blob/9459b9e82fc5a762fa1d6dcf4d24626de0a29feb/src/sys/handles.nim#L101

Hey, great work on this library! Very clean. I hope it's in Nim 2.0!

I'm currently making a PR for a `setNonBlocking` proc in Nim. I ran into an issue with FreeRTOS though. Its `fcntl` impl seems (I don't *know*) to be dependent on the hardware and other extensions it is built with. But so far, I don't think anything other than setting socket FDs to non-blocking works.

If the handle types were all distinct in current Nim, then I could do something like this to cover FreeRTOS:
```nim
proc setNonBlocking(fd: cint, nonBlocking = true)
when defined freertos:
  proc setNonBlocking(fd: FileHandle, nonBlocking = true)
    {.error: "Not available for FreeRTOS".}
else:
  proc setNonBlocking(fd: FileHandle, nonBlocking = true) =
    setNonBlocking(cint(fd), nonBlocking)
proc setNonBlocking(fd: SocketHandle, nonBlocking = true) =
  setNonBlocking(cint(fd), nonBlocking)
```

How would you handle this scenario with your API?
Maybe something like this, where it can be overriden if the user is using a FreeRTOS arch that fully implements `fcntl`:
```nim
# handles_posix.nim
const hasFileNonBlock {.booldefine.} = defined(posix) and not defined(freertos)

template setBlockingImpl() {.dirty.} =
  when hasFileNonBlock and not (fd is SocketFD):
    {.error: "Platform doesn't support setting non-block property of file handles.".}
```

Also, aren't FDs blocking by default? If so, then why have your API be `setBlocking` instead of `setNonBlocking`? Wouldn't your API require the `blocking` param to be set to `false` for the most comon use case?

```nim
stdin.setBlocking false
stdin.setBlocking true
# vs
stdin.setNonBlocking
stdin.setNonBlocking false
# I don't know, now that I see them both, maybe your way is cleaner.
```

One more thing: You differentiate sockets from other handles. Why not have a handle for other types like anonymous pipes, etc? This would allow handling of incomplete platform impls like the FreeRTOS example above.

**Comment by alaviss** [comment]
Thanks for your interest and the compliments :smile: 

> I'm currently making a PR for a `setNonBlocking` proc in Nim. I ran into an issue with FreeRTOS though. Its `fcntl` impl seems (I don't _know_) to be dependent on the hardware and other extensions it is built with. But so far, I don't think anything other than setting socket FDs to non-blocking works.

What you might be seeing is an unfortunate result of the POSIX specification according to [wisdom on the Internet](https://www.remlab.net/op/nonblock.shtml) (I couldn't track down the specific passage in POSIX spec):

> Regular files are always readable and they are also always writeable. This is clearly stated in the relevant POSIX specifications. I cannot stress this enough. Putting a regular file in non-blocking has ABSOLUTELY no effects other than changing one bit in the file flags.

> Nevertheless, non-blocking mode will not fix it. It will simply not work. Checking a file for readability or writeability always succeeds immediately. If the system needs time to perform the I/O operation, it will put the task in non-interruptible sleep from the read or write system call.

So, unfortunately, `O_NONBLOCK` will *never* work on regular files, and there is no way around that (there are other ways to do AIO on them, though). On most OS this won't result in an error though, but maybe FreeRTOS devs are trying to prevent people from assuming wrong things. 

> How would you handle this scenario with your API?

The `nim-sys` solution is to educate the user. This is usually done via a "Platform specific details" section in the procedure documentation. When you are working on `FD`, we assume that you have some familiarity with the underlying operating system, but we will provide you with some details on minute differences that could be overlooked. Proper abstractions are left to other modules to implement (read more below).

This solution won't fly upstream though, see https://github.com/nim-lang/Nim/pull/15093 and its verdict.

> Also, aren't FDs blocking by default? If so, then why have your API be `setBlocking` instead of `setNonBlocking`? Wouldn't your API require the `blocking` param to be set to `false` for the most comon use case?

As you can see, it's just shorter and easier to reason about in code when you are working with a positive value ("Blocking"). But it's personal taste and have no technical bearing.

> You differentiate sockets from other handles. Why not have a handle for other types like anonymous pipes, etc? This would allow handling of incomplete platform impls like the FreeRTOS example above.

The main reason is that `nim-sys` do not work in pure `FD`. As it is right now, an `FD` will only be `distinct`-ed if one of the following are true:

- It supports specialized functions and has no bearing to being an IO device: this is the category that `kqueue.FD` and `epoll.FD` falls into, both of which doesn't act like files.

- It requires the use of a different function for the same purpose: which is the reason why `SocketFD` is a `distinct`. On Windows, closing a socket has to be done with `closesocket()` and not the typical `CloseHandle()`.

The definition of `FD` here is a "resource handle" and it is treated as if it is an untyped pointer given to us by the OS. This also means that we assume you know a thing or two about the underlying platform. Other than `close`, all other procedures are there to help with other modules implementations, and since they are useful to our implementations, I have them exported because they might be useful to others as well. But those are *not* full-fledged abstractions of the underlying platform and instead of handling all details to make it transparent, we educate the user to lookout for unusual cases. 

All that allows the type structure to be simplified into this:

```
FD -> File -> WritePipe/ReadPipe
```

instead of

```
FD -> PipeFD -> WritePipe/ReadPipe
   |
   -> File
```

and enables more code reuse, which is important for other modules as they are the ones that do the heavy lifting of abstraction.

This decision is not firm. It is chosen because it greatly reduces implementation complexity (one set of abstractions), but this might be changed once we got a better idea of the requirements from other modules.

**Comment by quantimnot** [comment]
> So, unfortunately, O_NONBLOCK will never work on regular files,

I should have been more clear. I'm working with anonymous pipes for process handling.

> we assume that you have some familiarity with the underlying operating system, but we > will provide you with some details on minute differences that could be overlooked. Proper abstractions are left to other modules to implement (read more below).
>
> This solution won't fly upstream though, see nim-lang/Nim#15093 and its verdict.

That's a fine approach. It's a shame the documentation in nim-lang/Nim#15093 wasn't merged. I appreciate documented caveats.

I look forward to your progress. I will use it for my projects and contribute where I can.
